 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/other_events_lists", type: :request do
  
  # OtherEventsList. As you add validations to OtherEventsList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OtherEventsList.create! valid_attributes
      get other_events_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      other_events_list = OtherEventsList.create! valid_attributes
      get other_events_list_url(other_events_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_other_events_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      other_events_list = OtherEventsList.create! valid_attributes
      get edit_other_events_list_url(other_events_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OtherEventsList" do
        expect {
          post other_events_lists_url, params: { other_events_list: valid_attributes }
        }.to change(OtherEventsList, :count).by(1)
      end

      it "redirects to the created other_events_list" do
        post other_events_lists_url, params: { other_events_list: valid_attributes }
        expect(response).to redirect_to(other_events_list_url(OtherEventsList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OtherEventsList" do
        expect {
          post other_events_lists_url, params: { other_events_list: invalid_attributes }
        }.to change(OtherEventsList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post other_events_lists_url, params: { other_events_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested other_events_list" do
        other_events_list = OtherEventsList.create! valid_attributes
        patch other_events_list_url(other_events_list), params: { other_events_list: new_attributes }
        other_events_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the other_events_list" do
        other_events_list = OtherEventsList.create! valid_attributes
        patch other_events_list_url(other_events_list), params: { other_events_list: new_attributes }
        other_events_list.reload
        expect(response).to redirect_to(other_events_list_url(other_events_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        other_events_list = OtherEventsList.create! valid_attributes
        patch other_events_list_url(other_events_list), params: { other_events_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested other_events_list" do
      other_events_list = OtherEventsList.create! valid_attributes
      expect {
        delete other_events_list_url(other_events_list)
      }.to change(OtherEventsList, :count).by(-1)
    end

    it "redirects to the other_events_lists list" do
      other_events_list = OtherEventsList.create! valid_attributes
      delete other_events_list_url(other_events_list)
      expect(response).to redirect_to(other_events_lists_url)
    end
  end
end
